import { Symptom, Risk, Therapy, Medication, Disease } from "@/types/depression";

export const symptomsData: Symptom[] = [
  {
    id: 1,
    name: "头痛",
    description: "持续性或间歇性头部疼痛，可能伴有恶心或视觉障碍",
    createTime: "2025-03-20T10:00:00Z",
    updateTime: "2025-03-21T12:00:00Z",
    category: "身体",
    severity: 7,
    duration: "数小时至数天",
    isCommon: true,
    manifestations: '偏头痛;紧张性头痛;丛集性头痛'
  },
  {
    id: 2,
    name: "焦虑",
    description: "过度担忧和紧张感，伴随心悸和出汗",
    createTime: "2025-03-15T14:30:00Z",
    updateTime: "2025-03-21T13:00:00Z",
    category: "情绪",
    severity: 5,
    duration: "持续数周",
    isCommon: true,
    manifestations: "心悸;胸闷;失眠"
  },
];

export const risksData: Risk[] = [
  {
    id: 1,
    name: "高血压家族史",
    description: "一级亲属中有高血压病史",
    createTime: "2025-02-01T08:00:00Z",
    updateTime: "2025-03-01T09:00:00Z",
    category: "生物学",
    impactFactor: 0.6,
    evidenceLevel: "A",
    preventiveMeasures: "定期体检;低盐饮食",
  },
  {
    id: 2,
    name: "长期吸烟",
    description: "每天吸烟超过一包，持续超过5年",
    createTime: "2025-02-10T10:30:00Z",
    updateTime: "2025-03-05T11:00:00Z",
    category: "行为",
    impactFactor: 0.8,
    evidenceLevel: "B",
    preventiveMeasures: "戒烟计划;心理咨询",
  },
];

export const therapiesData: Therapy[] = [
  {
    id: 1,
    name: "认知行为疗法",
    description: "通过改变负面思维模式来改善情绪",
    createTime: "2025-03-01T09:00:00Z",
    updateTime: "2025-03-20T10:00:00Z",
    category: "心理治疗",
    approach: "逐步识别和挑战负性思维",
    durationCourse: "每周一次，持续3个月",
    sideEffects: "可能引发短暂焦虑",
  },
  {
    id: 2,
    name: "物理治疗",
    description: "针对肌肉和骨骼系统的康复训练",
    createTime: "2025-03-02T09:00:00Z",
    updateTime: "2025-03-20T10:00:00Z",
    category: "物理治疗",
    approach: "拉伸和力量训练",
    durationCourse: "每周两次，持续2个月",
    sideEffects: "肌肉酸痛",
  },
];

export const medicationsData: Medication[] = [
  {
    id: 1,
    name: "阿司匹林",
    description: "非甾体抗炎药，用于缓解疼痛和降低发热",
    createTime: "2025-03-01T08:00:00Z",
    updateTime: "2025-03-21T09:00:00Z",
    genericName: "Aspirin",
    brandNames: "拜阿司匹林;博蒙",
    drugClass: "NSAIDs",
    mechanism: "抑制前列腺素合成",
    dosage: "每日100mg",
    administrationRoute: "口服",
    sideEffects: "胃肠不适;胃溃疡",
    contraindications: "胃溃疡病史;出血性疾病",
    interactions: "华法林;地高辛",
  },
  {
    id: 2,
    name: "氯硝西泮",
    description: "用于缓解焦虑和睡眠障碍的镇静药",
    createTime: "2025-03-02T09:00:00Z",
    updateTime: "2025-03-21T10:00:00Z",
    genericName: "Clonazepam",
    brandNames: "利眠宁",
    drugClass: "苯二氮卓类",
    mechanism: "增强GABA受体活性",
    dosage: "每晚1mg",
    administrationRoute: "口服",
    sideEffects: "嗜睡;头晕",
    contraindications: "严重呼吸抑制",
    interactions: "酒精;巴比妥类",
  },
];

export const diseasesData: Disease[] = [
  {
    id: 1,
    name: "偏头痛",
    description: "反复发作的剧烈头痛，通常伴有恶心和视觉障碍",
    createTime: "2025-03-01T09:00:00Z",
    updateTime: "2025-03-21T10:00:00Z",
    medicalCode: "G43.0",
    category: "神经系统疾病",
    synonyms: "Migraine",
    prevalenceRate: 0.12,
    diagnosticCriteria: "根据国际头痛协会标准",
    symptoms: new Set([symptomsData[0]]),
    riskFactors: new Set([risksData[1]]),
    treatments: new Set([therapiesData[0]]),
    medications: new Set([medicationsData[0]]),
  },
  {
    id: 2,
    name: "广泛性焦虑障碍",
    description: "持续性焦虑和担忧，影响日常生活",
    createTime: "2025-03-02T10:00:00Z",
    updateTime: "2025-03-21T11:00:00Z",
    medicalCode: "F41.1",
    category: "精神障碍",
    synonyms: "GAD",
    prevalenceRate: 0.05,
    diagnosticCriteria: "DSM-5标准",
    symptoms: new Set([symptomsData[1]]),
    riskFactors: new Set([risksData[0]]),
    treatments: new Set([therapiesData[0]]),
    medications: new Set([medicationsData[1]]),
  },
];
